# Conexao Local (comentada)
#spring.data.mongodb.uri=mongodb://localhost:27017/workshop_mongo

# Conexao MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://edsonney_db_user:${MONGO_ATLAS_PASSWORD}@aws-cloud-webflux-mongo.98dtigw.mongodb.net/workshop_mongo?retryWrites=true&w=majority&appName=aws-cloud-webflux-mongo
